// Embedded monospaced bitmap font descriptor.
//
// The glyph data is generated by scripts/gen_font.py into Font5x7.cpp. A Font is
// a flat row-major table: each character occupies `height` bytes, one row per
// byte with the most significant bit as the leftmost pixel.
#pragma once

#include <cstdint>

namespace habitui {

struct Font {
  uint8_t width;        // cell width in pixels (<= 8)
  uint8_t height;       // cell height in pixels
  uint8_t first;        // first ASCII codepoint in the table
  uint8_t last;         // last ASCII codepoint in the table
  const uint8_t* rows;  // (last-first+1) * height bytes, row-major

  // Pointer to the first row byte of a glyph, or the '?' glyph for anything out
  // of range so callers never index past the table.
  const uint8_t* glyph(char c) const {
    uint8_t cp = static_cast<uint8_t>(c);
    if (cp < first || cp > last) cp = static_cast<uint8_t>('?');
    if (cp < first || cp > last) cp = first;
    return rows + static_cast<int>(cp - first) * height;
  }
};

const Font& defaultFont();

}  // namespace habitui
