// 1-bit icon bitmaps for the built-in icon set.
//
// Data is generated by scripts/gen_icons.py into Icons.cpp. Each icon is a
// square bitmap, row-major, MSB as the leftmost pixel, a set bit meaning ink.
// Row stride is (size + 7) / 8 bytes.
#pragma once

#include <cstdint>

#include "habitcore/IconSet.h"

namespace habitui {

struct IconBitmap {
  int size;             // width == height in pixels
  const uint8_t* data;  // size * ((size + 7) / 8) bytes
};

const IconBitmap& iconBitmap(habitcore::IconId id);

}  // namespace habitui
