#!/usr/bin/env python3
"""Generate the HabitInk embedded bitmap font.

The firmware draws short labels and numbers on a 1-bit e-ink panel, so it needs
a small monospaced ASCII font baked into flash. This script renders Pillow's
built-in bitmap font (a permissively licensed HPND-style font) into a fixed
cell and emits a committed C++ source file. The output is checked in, so
neither the firmware build nor CI depends on Pillow.

Run from the repo root:

    python3 scripts/gen_font.py

It writes lib/HabitUI/src/Font8x13.cpp.
"""
from __future__ import annotations

from PIL import Image, ImageDraw, ImageFont

FIRST = 0x20
LAST = 0x7E
CELL_W = 8
CELL_H = 13


def render_glyph(font, ch: str) -> list[int]:
    img = Image.new("1", (CELL_W, CELL_H), 0)
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), ch, fill=1, font=font)
    rows = []
    px = img.load()
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if px[x, y]:
                bits |= 1 << (CELL_W - 1 - x)  # MSB is leftmost pixel
        rows.append(bits)
    return rows


def main() -> None:
    font = ImageFont.load_default()
    glyphs = []
    for cp in range(FIRST, LAST + 1):
        glyphs.append((cp, render_glyph(font, chr(cp))))

    lines = []
    lines.append("// GENERATED by scripts/gen_font.py -- do not edit by hand.")
    lines.append("//")
    lines.append("// A %dx%d monospaced ASCII font (0x%02X..0x%02X), one byte per row," % (CELL_W, CELL_H, FIRST, LAST))
    lines.append("// MSB = leftmost pixel. Derived from Pillow's built-in bitmap font")
    lines.append("// (HPND-style permissive licence, compatible with the project MIT licence).")
    lines.append('#include "habitui/Font.h"')
    lines.append("")
    lines.append("namespace habitui {")
    lines.append("")
    lines.append("namespace {")
    lines.append("// Row-major glyph bitmaps, %d rows each." % CELL_H)
    lines.append("const uint8_t kGlyphs[][%d] = {" % CELL_H)
    for cp, rows in glyphs:
        body = ", ".join("0x%02X" % r for r in rows)
        disp = chr(cp) if cp != 0x5C else "backslash"
        lines.append("    {%s},  // 0x%02X '%s'" % (body, cp, disp if cp != 0x20 else "space"))
    lines.append("};")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("const Font& defaultFont() {")
    lines.append("  static const Font font{%d, %d, 0x%02X, 0x%02X, &kGlyphs[0][0]};" % (CELL_W, CELL_H, FIRST, LAST))
    lines.append("  return font;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace habitui")
    lines.append("")

    out_path = "lib/HabitUI/src/Font8x13.cpp"
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote", out_path, "with", len(glyphs), "glyphs")


if __name__ == "__main__":
    main()
